lim:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 1
  heartBeatTime: 20000 # 心跳超时时间 单位毫秒
  brokerId: 1000
  loginModel: 3 # 1: 服务端模式 2: 客户端模式 3: 服务端和客户端模式
  loginUrl: http://127.0.0.1:8000/v1